import { z } from 'zod';

export const createStudentSchema = z.object({
  firstName: z.string({ required_error: 'First name is required' }).min(1, 'First name is required'),
  lastName: z.string().nullish().default(''),
  email: z.string({ required_error: 'Email is required', invalid_type_error: 'Email is required' }).trim().min(1, 'Email is required').email('Invalid email address'),
  admissionNo: z.string().nullish(),
  admissionNumber: z.string().nullish(),
  rollNo: z.string().nullish(),
  rollNumber: z.string().nullish(),
  departmentId: z.string().uuid().nullish(),
  department: z.string().nullish(),
  batchYear: z.string().nullish(),
  courseId: z.string().uuid().nullish(),
  courseName: z.string().nullish(),
  class: z.string().nullish(),
  sectionId: z.string().uuid().nullish(),
  section: z.string().nullish(),
  parentName: z.string().nullish(),
  fatherName: z.string().nullish(),
  parentPhone: z.string().regex(/^[0-9]{10}$/, 'Parent phone must be exactly 10 digits').nullish().or(z.literal('')),
  parentMobile: z.string().regex(/^[0-9]{10}$/, 'Parent phone must be exactly 10 digits').nullish().or(z.literal('')),
  phone: z.string().regex(/^[0-9]{10}$/, 'Phone number must be exactly 10 digits').nullish().or(z.literal('')),
  studentMobile: z.string().regex(/^[0-9]{10}$/, 'Phone number must be exactly 10 digits').nullish().or(z.literal('')),
  bloodGroup: z.string().nullish(),
  emergencyContact: z.string().nullish(),
  status: z.string().nullish().default('active'),
  address: z.string().nullish(),
  gender: z.string().nullish(),
  dob: z.string().nullish(),
  dateOfBirth: z.string().nullish(),
  residenceType: z.string().nullish().default('Day Scholar'),
  hostelBlockId: z.string().uuid().nullish(),
  hostelRoom: z.string().nullish(),
});

export const updateStudentSchema = createStudentSchema.partial();
